name : custom-action
on: 

 push:
  branches:
    - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run custom action
        uses: radhi-hudijan/lesson-3-demos/business-greetings-action@main